Final mobile version,
sergiogval/my-portfolio pull request #9
Opened 2021-08-20 22:24 UTC by sergiogval

Hi, CR! I'd like to stress that I worked on solo all the week, my partner had a personal leave and they did not mached me with anyone else. So, you will be se commitments done boy myself and one collegue. On this realise I implemented the full form functionality, as well as some hover effects at button & text inputs. You will notice that there is a CSS file that is no still on use. I'm trying to diferent files and call the according one with a meta tag on HTML. LLet me know if you have anty questions. I'm already have finiched the web version. I'll request a pull before the day ends.

2021-08-20 23:01 UTC, barackm requested changes
Hi @sergiogval, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 
![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 23:01 UTC, barackm commented on index.html
> +    <header>
- [ ] You have done a great job adding validation to your inputs, however, for now your contact form doesn't seem to look like the one in the Figma design, see the difference below 👇 
- Your design
![image](https://user-images.githubusercontent.com/55465133/130300341-c496a26f-d82e-4225-8f11-f201560810c7.png)

- Figma design
![image](https://user-images.githubusercontent.com/55465133/130300386-19827de9-3b57-4a12-99ba-1e0f2e464807.png)

As you can see:
- [ ] Your inputs are not taking the appropriate width
- [ ] The get in touch button is not the same as the one in Figma
- [ ] The font-size and font-family are not the same as in the Figma design
- [ ] There is an extra empty space at the right of your website
- [ ] It seems that you have forgotten to validate the `<textarea>`, people can submit the form without the message.
- [ ] Please let's add the button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template 👇 
![image](https://user-images.githubusercontent.com/55465133/130300851-418b7ff9-64bf-4ce7-8d1d-eedc42cecf61.png)


Can you please fix these issues 👍

2021-08-21 14:34 UTC, sergiogval commented on stylem.css
>    outline: none;
Change size of email input component

2021-08-21 14:34 UTC, sergiogval commented on stylem.css
>    order: 1;
Change the size of email input component.

2021-08-21 14:35 UTC, sergiogval commented on stylem.css
>    outline: none;
Change the size of comments component.

2021-08-21 14:36 UTC, sergiogval commented on stylem.css
>    color: white;
Change the form of submit button component.

2021-08-21 14:38 UTC, sergiogval commented on stylem.css
>    box-shadow: 5px 5px rgba(20, 25, 77, 0.08);
Change for a circle figure of the image, before it was a square.

2021-08-21 14:39 UTC, sergiogval commented on stylem.css
>  input.submit:hover {
Add a new class of text for the header of of cards on the portfolio section.

2021-08-21 14:48 UTC, sergiogval commented on index.html
>          <h2 class="text1">Multi-post Stories Gain+Glory</h2>
Changed element and class to match the template.

2021-08-21 15:08 UTC, sergiogval commented on stylem.css
>    grid-row: 2;
Recuerda cambiar esto en el archivo para web.

2021-08-21 15:09 UTC, sergiogval commented on stylem.css
>    box-sizing: border-box;
Change on item1,item2 & item3 to match the template.

2021-08-21 20:00 UTC, barackm requested changes
Hi @sergiogval, 👋 

Great work on making the changes requested by a previous reviewer 👏 👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 😉  😉 

 # STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-21 20:05 UTC, sergiogval commented on index.html
>              <label for="comments"></label>
![image](https://user-images.githubusercontent.com/67393791/130333630-6820344b-bf76-41ac-83a3-45e674357ab0.png)

2021-08-21 20:11 UTC, sergiogval commented on index.html
>              <label for="comments"></label>
ok I've just ran a "nxp hint ." command locally and it gave me no errors. So I'll a commit and will require the review again. The optional comments, will be consider for the desktop version commit.

2021-08-21 20:28 UTC, safafa approved these changes
## STATUS: APPROVED 🟢 👏
Hello, @sergiogval  great job working on the requested changes 👍 💯

Now you can merge this branch 💪 😄
HAPPY CODING!! AND GOOD LUCK WITH THE NEXT ONES 🤞 🍀

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-21 20:43 UTC, merged